package main

import (
	"context"
	"errors"
	"fmt"
	"log"
	"log/slog"
	"net/http"

	"connectrpc.com/connect"
	"connectrpc.com/validate"
	greetv1 "github.com/lao-tseu-is-alive/connect-go-example/gen/greet/v1"        // generated by protoc-gen-go
	"github.com/lao-tseu-is-alive/connect-go-example/gen/greet/v1/greetv1connect" // generated by protoc-gen-connect-go
	"github.com/lao-tseu-is-alive/go-cloud-k8s-common-libs/pkg/config"
	"github.com/lao-tseu-is-alive/go-cloud-k8s-common-libs/pkg/golog"
)

const (
	APP             = "greetServer"
	VERSION         = "0.0.2"
	AppVersion      = APP + " v" + VERSION
	defaultIp       = "127.0.0.1"
	defaultPort     = 8080
	defaultLogName  = "stderr"
	myHeaderKey     = "Acme-Tenant-Id"
	serverHeaderKey = "App-Version"
)

type GreetServer struct {
	Logger          *slog.Logger
	ClientHeaderKey string
}

func (s *GreetServer) Greet(ctx context.Context, req *greetv1.GreetRequest) (*greetv1.GreetResponse, error) {
	s.Logger.Info("entering Greet", "context", ctx, "request", req)
	if err := ctx.Err(); err != nil {
		return nil, err // automatically coded correctly
	}
	// let's retrieve client headers if any
	callInfo, ok := connect.CallInfoForHandlerContext(ctx)
	if !ok {
		return nil, errors.New("can't access headers: no CallInfo for handler context")
	}
	headerVal := callInfo.RequestHeader().Get(s.ClientHeaderKey)
	s.Logger.Info("retrieving special header", "headerKey", s.ClientHeaderKey, "headerValue", headerVal)

	res := &greetv1.GreetResponse{
		Greeting: fmt.Sprintf("Hello, %s!", req.Name),
	}
	//let's send back a server header
	callInfo.ResponseHeader().Set(serverHeaderKey, AppVersion)
	return res, nil
}

func main() {
	logWriter, err := config.GetLogWriter(defaultLogName)
	if err != nil {
		log.Fatalf("💥💥 error getting log writer: %v'\n", err)
	}
	logLevel, err := config.GetLogLevel(golog.InfoLevel)
	if err != nil {
		log.Fatalf("💥💥 error getting log level: %v'\n", err)
	}
	l := golog.NewLogger("simple", logWriter, logLevel, APP)
	l.Info("🚀 Starting", "app", APP, "version", VERSION)

	greeter := &GreetServer{Logger: l, ClientHeaderKey: myHeaderKey}
	mux := http.NewServeMux()
	path, handler := greetv1connect.NewGreetServiceHandler(
		greeter,
		// Validation via Protovalidate is almost always recommended
		connect.WithInterceptors(validate.NewInterceptor()),
	)
	mux.Handle(path, handler)
	p := new(http.Protocols)
	p.SetHTTP1(true)
	// Use h2c so we can serve HTTP/2 without TLS.
	p.SetUnencryptedHTTP2(true)
	serverAddress := fmt.Sprintf("%s:%d", defaultIp, defaultPort)
	l.Info("Will start server ...", "listenAddress", serverAddress)
	s := http.Server{
		Addr:      serverAddress,
		Handler:   mux,
		Protocols: p,
	}
	s.ListenAndServe()
}
