package main

import (
	"context"
	"log"
	"net/http"

	greetv1 "github.com/lao-tseu-is-alive/connect-go-example/gen/greet/v1"        // generated by protoc-gen-go
	"github.com/lao-tseu-is-alive/connect-go-example/gen/greet/v1/greetv1connect" // generated by protoc-gen-connect-go
)

func main() {
	client := greetv1connect.NewGreetServiceClient(
		http.DefaultClient,
		"http://localhost:8080",
	)
	res, err := client.Greet(
		context.Background(),
		&greetv1.GreetRequest{Name: "Jane"},
	)
	if err != nil {
		log.Println(err)
		return
	}
	log.Println(res.Greeting)
}
