package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"log/slog"
	"net/http"
	"time"

	"connectrpc.com/connect"
	greetv1 "github.com/lao-tseu-is-alive/connect-go-example/gen/greet/v1"        // generated by protoc-gen-go
	"github.com/lao-tseu-is-alive/connect-go-example/gen/greet/v1/greetv1connect" // generated by protoc-gen-connect-go
	"github.com/lao-tseu-is-alive/go-cloud-k8s-common-libs/pkg/config"
	"github.com/lao-tseu-is-alive/go-cloud-k8s-common-libs/pkg/golog"
)

const (
	APP            = "greetClient"
	VERSION        = "0.0.3"
	defaultName    = "connectRPC"
	defaultIp      = "127.0.0.1"
	defaultPort    = 8080
	defaultLogName = "stderr"
)

func main() {
	// Define flags
	bench := flag.Bool("bench", false, "Run benchmark")
	mode := flag.String("mode", "connect", "Protocol to use: 'connect' or 'grpc'")
	numMsgs := flag.Int("n", 1000, "Number of messages to send in benchmark mode")
	nameArg := flag.String("name", defaultName, "Name to greet")
	flag.Parse()

	logWriter, err := config.GetLogWriter(defaultLogName)
	if err != nil {
		log.Fatalf("💥💥 error getting log writer: %v'\n", err)
	}
	logLevel, err := config.GetLogLevel(golog.InfoLevel)
	if err != nil {
		log.Fatalf("💥💥 error getting log level: %v'\n", err)
	}
	l := golog.NewLogger("simple", logWriter, logLevel, APP)
	l.Info("🚀 Starting", "app", APP, "version", VERSION)

	// Determine name to greet (flag takes precedence, then args if any, then default)
	nameToGreet := *nameArg
	if nameToGreet == defaultName && len(flag.Args()) > 0 {
		nameToGreet = flag.Args()[0]
	}

	serverAddress := fmt.Sprintf("%s:%d", defaultIp, defaultPort)
	l.Info("Will call Greet to server", "listenAddress", serverAddress, "name", nameToGreet, "mode", *mode)

	reqUrl := fmt.Sprintf("http://%s", serverAddress)

	opts := []connect.ClientOption{}
	if *mode == "grpc" {
		opts = append(opts, connect.WithGRPC())
	}
	// If mode is connect, we use defaults (Connect Protocol + Protobuf format)

	client := greetv1connect.NewGreetServiceClient(
		http.DefaultClient,
		reqUrl,
		opts...,
	)

	if *bench {
		runBenchmark(client, *numMsgs, nameToGreet, l)
	} else {
		res, err := client.Greet(
			context.Background(),
			&greetv1.GreetRequest{Name: nameToGreet},
		)
		if err != nil {
			log.Println(err)
			return
		}
		log.Println(res.Greeting)
	}
}

func runBenchmark(client greetv1connect.GreetServiceClient, n int, name string, l *slog.Logger) {
	l.Info("Starting benchmark", "n", n, "name", name)
	start := time.Now()
	for i := 0; i < n; i++ {
		_, err := client.Greet(
			context.Background(),
			&greetv1.GreetRequest{Name: name},
		)
		if err != nil {
			log.Fatalf("Benchmark failed at request %d: %v", i, err)
		}
	}
	elapsed := time.Since(start)
	seconds := elapsed.Seconds()
	rps := float64(n) / seconds
	l.Info("Benchmark finished", "elapsed", elapsed, "rps", fmt.Sprintf("%.2f", rps))
	fmt.Printf("Benchmark: %d messages in %v | RPS: %.2f\n", n, elapsed, rps)
}
